### PR TITLE
Check if app has a mountpoint

### PR DESCRIPTION
**Pull request by grzegorz-jakubiak**
Related to https://github.com/prism-rb/prism/issues/2. I managed to come up with sth like this. I'd be grateful if you could provide me with instruction how to build the project so I could actually test if this is working.

### CODE REVIEW

**Comment by Widdershin** [comment]
Oooh thanks for this :) here are some instructions so you can try it out!

https://github.com/prism-rb/prism/blob/master/COMPILING.md

**Comment by grzegorz-jakubiak** [comment]
I tried it out and made it compile but I still lack some knowledge of both C and mruby. I mean I managed to find the appropriate function for the task and also the error but I'm not sure if I should first define `Prims::MountPoint` in our `main.c` to be able to use it? Or is there a way to get it's definition from app?

**Comment by Widdershin** [comment]
Hey @grzegorz-jakubiak I ended up finishing this off, I hope that's okay. I had to write the code to figure out how to help.

Check out 041d85e778da494d8ada44af9b9d193b15f08b3d.

Main things of interest:
  * I led you astray originally, since the name of the class was actually `Prism::Mount`, which is defined in `src/prism.rb`, sorry about that!
  * We needed to first look up the module and then the class inside of it

**Comment by grzegorz-jakubiak** [comment]
Not at all @Widdershin, thanks for help!

**Pull request merged**
