### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by grzegorz-jakubiak**
I hacked at `.travis.yml` so the C runtime can be built

### CODE REVIEW

**Comment by grzegorz-jakubiak** [comment]
I see that I can't set up travis for this repository

**Comment by Widdershin** [comment]
I set up Travis, will merge if this passes :)

**Comment by grzegorz-jakubiak** [comment]
I got it working with a small trick of specifying the generic language cause otherwise it wanted to run `bundle install` and errored out. Please have a look :wink:

**Comment by Widdershin** [comment]
Great work, thank you!

**Pull request merged**
