### PR TITLE
Use method_missing to build tags

### PR DESCRIPTION
**Pull request by grzegorz-jakubiak**
`#method_missing` gives us more flexibility and doesn't force providing array of tags and define method for each element in that array. I think in this case it's okay to use `method_missing` taking into account that HTML5 allows for custom elements.

### CODE REVIEW

**Comment by Widdershin** [comment]
Oooh interesting idea, this could cut down the bundle size a bit.

My biggest issue is that now if someone typos any variable name or method inside any `Prism::Component`, they won't get an error message any more, and might end up with a very confusing situation until they figure out that their typo has become a dom element.

We could consider defining `respond_to?`, but then we need a list of tags. We could at least let the user define a method for custom tags that should be available that way. That does have the downside that we need to re-include the list of tags.

What do you think?

**Comment by grzegorz-jakubiak** [comment]
I agree and I completely forgot about the error. I reincluded tag list and use simple check in method missing to invoke `super` when tag is not on the list. I think we should leave custom tags for now.

**Comment by grzegorz-jakubiak** [comment]
Funny enough I've found small bug in `method_missing` which makes it not provide name of actual missing method when `super` is called. I've created the issue https://github.com/mruby/mruby/issues/4820

**Comment by grzegorz-jakubiak** [comment]
I've just found that `method_missing` is actually (slower)[https://franck.verrot.fr/blog/2015/07/12/benchmarking-ruby-method-missing-and-define-method](not recent benchmark) than `define_method` and there's this bug that doesn't return the actual method name. I'll stick to `define_method` which is faster but turn the array into array of symbols

**Pull request closed without merging**
