### PR TITLE
Support require

### PR DESCRIPTION
**Pull request by grzegorz-jakubiak**
I started working on supporting `require` by using [mruby-require](https://github.com/mattn/mruby-require). However, it didn't prove to be that easy. I keep getting `cannot load such file ...` and I've tried multiple differents paths e.g `./prism/component` and with extension and so on. I couldn't find any solution online I haven't seen any complaint about it not working. Maybe I don't fully understand the `C` part of the implementation and some changes have to be made in order to make it work. I actually, also tried adding file in the same directory as `prism.rb` and requiring it from `prism.rb` also didn't work.

### CODE REVIEW

**Comment by Widdershin** [comment]
@grzegorz-jakubiak I think I know why it's not working.

All the filesystem access stuff actually runs against a virtual filesystem in memory. Part of the reason for this is that it helps the mruby interpreter correctly pick up line numbers for stack traces

We currently just load in `src/prism.rb` and the main file, so any additional files won't show up in there by default.

https://github.com/prism-rb/prism/blob/a573312d5ec86347350f8c54f8de75e75716a91e/src/prism.js#L101-L106

Here is the reference for the emscripten FS API we're working with: `https://emscripten.org/docs/api_reference/Filesystem-API.html`.

### HTTP
When we require a file that isn't loaded, we could request it from the server (as ruby code). This would be comparatively simple, but I think would have sub-par performance since require blocks.

For the HTTP option to be viable, I think we need a standard equivalent to the import syntax for JS. Something that allows us to load in multiple dependencies at once without violating Ruby's other semantics.

It could be something like a convention that all top level require statements prior to another ruby statement can be loaded in parallel, but are executed in sequence.

This approach has the advantage of easily supporting code splitting, since you would only load what you need for a given page. The disadvantage is that it's likely to be way slower, especially if the user doesn't have HTTP/2 support.

### Config
Require the user to specify all the files that need to be available in the in-memory fs. This is a decent option, but is quite a burden on the user to maintain. I could see this being a bit of a barrier to adoption.

### Analysis
We write a tool to statically analyze require statements across a ruby project, and the bundle them together. Effectively browserify for Ruby.

This is my personal favourite, although it would involve adding a compile step. I think that could be negated by integrating it into the server and eventual rails tooling.

What do you think? Can you see any options I've missed?

I might have a crack at prototyping the analysis tool this afternoon, I think a minimal version would be straightforward.

**Comment by grzegorz-jakubiak** [comment]
Oh, I see.

I think this is actually a good idea and I don't see any other possibility. Great! I think I could try and help when you have some code ready. 😉

**Comment by Widdershin** [comment]
Hey sorry about the lack of followup!

I wrote a tool last week that would analyze require statements and make a bundle that could be loaded into the emscripten in memory FS. I then ran into an issue with that require library, where if were requiring inside of a require we'd get cryptic longjmp errors.

I tooled around with my own implementation of require but had similar issues. I think the easiest strategy for the moment might actually be flattening out the dependency graph so that each module gets loaded one at a time, and then perhaps only included in the scope when require is called. I'll find some time soon to push up my prototype.

**Comment by grzegorz-jakubiak** [comment]
@Widdershin are you still working on this implementation?

**Comment by Widdershin** [comment]
@grzegorz-jakubiak nah I haven't touched require support in a while.

I forgot to update but I did some investigation and ended up with some mysterious segfault issues I was struggling to debug. Check out  1c2dc6e8765263ff9e6502c8f388be7cae9dd444 for my WIP stuff.

When I did some stuff with Prism more recently I was just catting the files together but I can see that's not ideal. When I get back to doing more Prism stuff again I might try this require support again, but if you want to have a look be my guest :)

**Comment by Widdershin** [comment]
Actually from looking at that branch now it seems like it's not segfaulting, but there are definitely some mysterious errors going on.

If you want to try it out there's a nice server in there that does the bundling and everyone, if you run `ruby src/server.rb`

**Comment by Widdershin** [comment]
Hey @grzegorz-jakubiak,

I managed to sort out those issues, turned out that I was accidentally catching control flow exceptions from inside of the emscripten runtime.

I've implemented basic require support in the master branch, check it out if you're interested.

**Comment by grzegorz-jakubiak** [comment]
Got it! I’m closing this one then!

**Pull request closed without merging**
